# Generated by Django 2.1.2 on 2018-10-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimezone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('images', models.ImageField(blank=True, null=True, upload_to='post_images')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crimezone_app.UserProfile')),
            ],
        ),
    ]
