# Generated by Django 2.1.2 on 2018-10-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimezone_app', '0002_crimepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimepost',
            name='title',
            field=models.TextField(),
        ),
    ]
