# Generated by Django 2.1.2 on 2018-12-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimezone_app', '0007_auto_20181109_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Common User'), (2, 'Action Applier')], null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
