# Generated by Django 2.1.2 on 2018-12-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimezone_app', '0008_auto_20181217_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Common User'), (2, 'Action Applier')], default=1, null=True),
        ),
    ]
