# Generated by Django 2.1.2 on 2018-12-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimezone_app', '0009_auto_20181222_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimepost',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
